NUM_CLIENTS=4
NUM_BACKUPS=0
NUM_COUCHBASE_SERVERS_DATA_CLUSTER1=30
NUM_COUCHBASE_SERVERS_DATA_CLUSTER2=0
NUM_COUCHBASE_SERVERS_DATA_CLUSTER1_NEW=0
NUM_COUCHBASE_SERVERS_DATA_CLUSTER2_NEW=0
NUM_COUCHBASE_SERVERS_INDEX=0
NUM_COUCHBASE_SERVERS_QUERY=0


CLUSTER1_NUM_SERVER_GROUPS=1

CLUSTER1_AVAILABILITY_ZONE="us-east-1a"
CLUSTER2_AVAILABILITY_ZONE="us-east-1c"

CLIENT_INSTANCE_TYPE="c3.xlarge"
COUCHBASE_INSTANCE_TYPE="r3.4xlarge" #c3.8xlarge"
BACKUP_INSTANCE_TYPE="m4.2xlarge"

CLIENT_IMAGE= "ami-3eb8fd54"
COUCHBASE_IMAGE="ami-a63677cc"
BACKUP_IMAGE="ami-zzzzz"
BACKUP_SPACE="100"
S3_BUCKET_NAME="scalability-mcafee"
